// responseMessage.js
module.exports = {
    NULL_VALUE: "필요한 값이 없습니다.",
    OUT_OF_VALUE: "파라미터 값이 잘못 되었습니다.",
    INTERNAL_SERVER_ERROR: "서버 내부 오류",

    USER_START_SUCCESS: "앱 시작 성공",
    PWD_UPDATE_SUCCESS: "유저 업데이트 성공",
    USER_UPDATE_FAIL: "유저 업데이트 실패",
    SIGN_IN_SUCCESS: "로그인 성공",
    SIGN_IN_FAIL: "로그인 실패",
    NO_USER: "존재하지 않는 유저입니다.",
    MISS_MATCH_PW: "비밀번호가 일치하지 않습니다",
    EXPIRED_TOKEN: "만료된 토큰입니다",
    INVALID_TOKEN: "유효하지 않은 토큰입니다",
    EMPTY_TOKEN: "토큰이 없습니다",
    USER_UPDATE_FAIL:"유저 추가 실패",
    EXIST_DATA: "데이터가 있습니다.",
    NO_DATA:"데이터가 없습니다.",

    PHONE_NUM_UPDATE_SUCCESS: "전화번호 변경 성공",

    CARD_CREATE_SUCCESS: "카드 작성 성공",
    CARD_CREATE_FAIL: "카드 작성 실패",
    CARD_READ_ALL_SUCCESS: "카드 전체 조회 성공",
    CARD_READ_ALL_FAIL: "카드 전체 조회 실패",
    CARD_READ_VISIBLE_FAIL: "장애인용 카드 전체 조회 실패",
    CARD_READ_VISIBLE_SUCCESS: "장애인용 카드 전체 조회 성공",
    CARD_READ_SUCCESS: "카드 조회 성공",
    CARD_READ_FAIL: "카드 조회 실패",
    CARD_UPDATE_SUCCESS: "카드 수정 성공",
    CARD_UPDATE_FAIL: "카드 수정 실패",
    CARD_DOWNLOAD_SUCCESS: "카드 다운로드 성공",
    CARD_DELETE_SUCCESS: "카드 삭제 성공",
    CARD_DELETE_FAIL: "카드 삭제 실패",
    CARD_COUNT_SUCCESS: "카드 클릭 횟수 증가 성공",
    CARD_COUNT_FAIL: "카드 클릭 횟수 증가 실패",
    ALREADY_ID: "존재하는 ID 입니다.",
    NO_CARD: "존재하지 않는 카드 입니다.",
    CARD_HIDE_SUCCESS: "카드 숨기기 성공",
    CARD_HIDE_FAIL: "카드 숨기기 실패",
}